baseurl: "https://gzy-dayu.cn/"
languageCode: "en-us"
title: "Another_Dayu"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100
##utterances
---
params:
  utteranc:
    enable: true
    repo: DayuGuo/blogtalks-utterances
    issueTerm: pathname
    theme: github-light
---
permalinks:
  cn: "/:sections/:year/:month/:slug/"
  en: "/:sections/:year/:month/:slug/"
